Tickets report
sebas746/GanaPagaAdminWebApplication pull request #26
Opened 2023-12-30 14:29 UTC by raularango85

2024-01-09 12:53 UTC, dannytp91 requested changes

2024-01-09 12:53 UTC, dannytp91 commented on src/app/components/Tables/Reports/Ticket/TicketReportTable.tsx
> +                              {isTicketDetailLoading ? (
Try to simplify this using COnditional Rendering Component

2024-01-09 12:53 UTC, dannytp91 commented on src/app/components/Tables/Reports/Ticket/TicketReportTable.tsx
> +        {!isLoading && ticketReportPaginated && ticketReportPaginated.ticketsCount > 0 && (
when you have multiples conditions to render something, create a variable with a describable name

2024-01-09 12:53 UTC, dannytp91 commented on src/app/components/Tables/Reports/Ticket/TicketReportTable.tsx
> +        {!isLoading &&
Use Conditional Rendering for this

2024-01-09 12:53 UTC, dannytp91 commented on src/app/components/Tables/Reports/Ticket/TicketReportTable.tsx
> +                <button
React Bootstrap has components ready for this

2024-01-09 12:53 UTC, dannytp91 commented on src/app/pages/reports/sales/TicketReport/TicketReport.hook.ts
> +  const fetchVesData = async () => {
USe React query

2024-01-09 12:53 UTC, dannytp91 commented on src/app/pages/reports/sales/TicketReport/TicketReport.tsx
> +        {currencies.map((currency) => (
Create a variable with useMemo, to avoid render this multiples times

const currenciesMemo = useMemo(() => {}, [currencies])

2024-01-09 12:53 UTC, dannytp91 commented on src/app/pages/reports/sales/TicketReport/TicketReport.tsx
> +        {ticketDetailId && (
COnditional Rendering

2024-01-10 15:20 UTC, raularango85 commented on src/app/pages/reports/sales/TicketReport/TicketReport.hook.ts
> +  const fetchVesData = async () => {
I just separated logic into 2 functions.

2024-01-10 16:07 UTC, dannytp91 requested changes

2024-01-10 16:07 UTC, dannytp91 commented on src/app/pages/reports/sales/TicketReport/TicketReport.tsx
> +        {currency.currencyId === CurrencyId.USD && ticketReportUsdState.ticketReportPaginated && (
remember create a variable to avoid complexity reading code

2024-01-10 16:07 UTC, dannytp91 commented on src/app/pages/reports/sales/TicketReport/TicketReport.tsx
> +        {currency.currencyId === CurrencyId.VES && ticketReportVesState.ticketReportPaginated && (
same here

2024-01-15 14:47 UTC, dannytp91 approved these changes

2024-01-15 14:48 UTC, merged